### ISSUE TITLE
resultToAsync works with @0.10.2, but not latest version

### ISSUE THREAD

**Issue by zhentian-wan** [evilsoft/crocks#399]
**Describe the bug**

I am following the youtube lesson, https://youtu.be/O1Gu5b7rxbw?t=2885, `resultToAsync` works for crocks@0.10.2 version, but not 0.11.0 & 0.11.1 versions.

**To Reproduce**
```js
import { readFile } from "fs";
import { Async, tryCatch, resultToAsync } from "crocks";

const e = e => console.error("rej", e);
const s = s => console.log("res", s);

const parse = tryCatch(JSON.parse);
const readFileAsync = Async.fromNode(readFile);
readFileAsync("config.json", "utf8")
  .chain(resultToAsync(parse))
  .fork(e, s);
```
Error is `throw new TypeError('resultToAsync: Result returning function required`

**Comment by evilsoft** [comment]
hmmm. what version of node are you using?
I am able to get this to run as expected with 0.11.1.

**Comment by zhentian-wan** [comment]
my node version is 10.14.2

**Comment by evilsoft** [comment]
@zhentian-wan we just released a new version. Please give it a shot and see if this does anything for you.

I'm going to close out this issue for now, if you continue to have problems, please reopen or create a new issue. Hope this helps

**Comment by zhentian-wan** [comment]
Hi, Congrats for new release!

I have installed and test out, looks like the problem is still here.

I found out that, if file doesn't exists, then it actually works:
```
rej { [Error: ENOENT: no such file or directory, open 'config.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'config.json' }
```

If the file exists, then it crashes with error: `TypeError: resultToAsync: Result returning function required`

I can make it works when file exists by doing one extra function invoke:
```
const { readFile } = require("fs");
const { Async, tryCatch, resultToAsync } = require("crocks");

const e = e => console.error("rej", e);
const s = s => console.log("res", s);

const parse = tryCatch(JSON.parse);
const readFileAsync = Async.fromNode(readFile);
readFileAsync("exists.json", "utf8")
  .map(parse)
  .map(fn => fn())
  .chain(resultToAsync)
  .fork(e, s);
```

Hope this information helps.

**Comment by dalefrancis88** [comment]
Yeah so i've seen a similiar issue in exactly this, It is caused because JSON.parse is not a unary function. The output of any call to `tryCatch` regardless of the input is curried. This is why you need to do the extra call with JSON.parse

import `unary` as well from crocks and wrap parse with it and that will drop the need for the extra `map`

`const parse = tryCatch(unary(JSON.parse))`

**Comment by zhentian-wan** [comment]
> Yeah so i've seen a similiar issue in exactly this, It is caused because JSON.parse is not a unary function. The output of any call to `tryCatch` regardless of the input is curried. This is why you need to do the extra call with JSON.parse
> 
> import `unary` as well from crocks and wrap parse with it and that will drop the need for the extra `map`
> 
> `const parse = tryCatch(unary(JSON.parse))`

Cool! Thanks for the infromation 👍

**Comment by dalefrancis88** [comment]
Glad i could help 😄
